In [9]:
# 1
import numpy as np
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
# 2

m = np.zeros((3, 3), dtype=float) 
print(m)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# 3

b = np.random.randint(1, 11, size=(5, 5))
print(b)

[[ 4  9  5  5  6]
 [ 1  2 10  9  8]
 [ 8  2  3  7  3]
 [ 8  3  2  7  6]
 [ 6  1  5  9  1]]


In [14]:
# 4

b = np.random.random((4, 4))
print(b)

[[0.7449654  0.77901642 0.37124641 0.26185894]
 [0.86568015 0.02056243 0.51409752 0.94477572]
 [0.82958547 0.42687845 0.8267532  0.46051314]
 [0.3642041  0.12934594 0.07747686 0.87870524]]


In [20]:
# 5

a = np.random.randint(1, 10, size=5)
b = np.random.randint(1, 10, size=5)
print(a + b)
print(a - b)
print(a * b)

[ 9  4  5 12  5]
[-5  0  1  2 -1]
[14  4  6 35  6]


In [22]:
# 6

a = np.random.randint(1, 10, size=7)
b = np.random.randint(1, 10, size=7)
print(np.dot(a, b))


288


In [25]:
# 7

a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
c = np.dot(a, b)
print(c)

[[50 22 40]
 [50 28 25]]


In [27]:
# 8

a = np.random.randint(1, 10, size=(3, 3))
a_inv = np.linalg.inv(a)
print(a_inv)

[[-3.33333333e-01 -7.14285714e-01  9.28571429e-01]
 [-6.34413157e-17  4.28571429e-01 -3.57142857e-01]
 [ 3.33333333e-01  1.42857143e-01 -2.85714286e-01]]


In [35]:
# 9

a = np.random.random((4, 4))
b = a.T
print(b)

[[0.90622109 0.02894503 0.96641544 0.29324625]
 [0.89202752 0.52975403 0.89000297 0.42117826]
 [0.34167389 0.6085377  0.1423913  0.20276764]
 [0.41101448 0.49157548 0.84532309 0.24598245]]


In [37]:
# 10

m = np.random.randint(1, 10, size=(3, 4))
v = np.random.randint(1, 10, size=4)
c = m * v
print(c)

[[ 4 18 63  7]
 [28 14 28 28]
 [ 8 18 28 21]]


In [40]:
# 11

m = np.random.random((2, 3))
v = np.random.random(3)
c = m * v
print(c)

[[0.14693869 0.20885938 0.01074047]
 [0.02890867 0.21555249 0.00350357]]


In [41]:
# 12

m1 = np.random.randint(1, 10, size=(2, 2))
m2 = np.random.randint(1, 10, size=(2, 2))
c = m1 * m2
print(c)

[[20  6]
 [ 3  7]]


In [42]:
# 13

m1 = np.random.randint(1, 10, size=(2, 2))
m2 = np.random.randint(1, 10, size=(2, 2))
c = m1 + m2
print(c)

[[16  9]
 [15  9]]


In [45]:
# 14

m = np.random.randint(1, 100, size=(5, 5))
print(m.sum())

1279


In [46]:
# 15

m1 = np.random.randint(1, 10, size=(4, 4))
m2 = np.random.randint(1, 10, size=(4, 4))
c = m1 - m2
print(c)

[[ 2  3 -4  0]
 [-4 -8  2  7]
 [ 1 -2 -2  5]
 [-4 -3 -1 -5]]


In [54]:
# 16

m = np.random.random((3, 3))
print(m[0].sum())
print(m[1].sum())
print(m[2].sum())

1.5579474354335556
0.49460583804749125
1.3234263770026828


In [66]:
# 17

m = np.array(([2, 4, 2, 8], [3, 3, 4, 5], [3, 2, 8, 5]))
sq = np.square(m)
print(sq)

[[ 4 16  4 64]
 [ 9  9 16 25]
 [ 9  4 64 25]]


In [67]:
# 18

v = np.array([2, 3, 4, 5])
sq = np.square(v)
print(sq)

[ 4  9 16 25]
